-- 코드를 입력하세요
SELECT TITLE, R.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD U
JOIN USED_GOODS_REPLY R on U.BOARD_ID = R.BOARD_ID
WHERE U.CREATED_DATE LIKE "2022-10%"
ORDER BY  R.CREATED_DATE, TITLE