SELECT F.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN
(
SELECT PRODUCT_ID, CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT
WHERE CATEGORY REGEXP "과자|국|김치|식용유"
GROUP BY CATEGORY
) MP ON F.CATEGORY = MP.CATEGORY AND F.PRICE = MAX_PRICE

ORDER BY MAX_PRICE DESC